// 레퍼런스 카드 밑 대표 태그(SCR-ARCH-05) 한국어 라벨.
//   Unsplash rawTags 는 영어 자유 단어(수천 종)라 고정 번역이 불가능하다. 실제 코퍼스(2.4만 이미지)의
//   빈도 상위 ~300개를 데이터 기반으로 매핑해, 실사용 태그의 대부분을 한국어로 덮는다.
//   AI 이미지 태그(ImageDraweTag subject/technique/mood)는 이미 한국어라 매핑에 없으면 원문을 그대로 쓴다.
//   즉 매핑 규칙: (1) 매핑에 있으면 한글, (2) 한글이 이미 섞인 값이면 원문 유지, (3) 그 외 영어는 숨김.

// eslint-disable-next-line
const TAG_KO = {
  // 자연·풍경
  nature: "자연",
  outdoors: "야외",
  landscape: "풍경",
  scenery: "경치",
  scenic: "경치",
  wilderness: "대자연",
  countryside: "시골",
  rural: "시골",
  urban: "도시",
  city: "도시",
  town: "마을",
  neighborhood: "동네",
  village: "마을",
  environment: "환경",
  panoramic: "파노라마",
  "aerial view": "항공뷰",
  horizon: "지평선",
  background: "배경",
  backgrounds: "배경",
  wallpaper: "배경화면",
  wallpapers: "배경화면",
  pattern: "패턴",
  texture: "질감",
  travel: "여행",
  adventure: "모험",
  // 지형·땅
  land: "땅",
  ground: "지면",
  soil: "흙",
  dirt: "흙",
  "dirt road": "흙길",
  field: "들판",
  grassland: "초원",
  meadow: "초원",
  plain: "평원",
  plateau: "고원",
  valley: "계곡",
  canyon: "협곡",
  cliff: "절벽",
  promontory: "곶",
  mesa: "메사",
  slope: "비탈",
  hill: "언덕",
  mountain: "산",
  mountains: "산",
  "mountain range": "산맥",
  "mountainous landforms": "산악지형",
  peak: "봉우리",
  summit: "정상",
  ridge: "능선",
  rock: "바위",
  rocks: "바위",
  stone: "돌",
  boulder: "바위",
  cave: "동굴",
  desert: "사막",
  dune: "모래언덕",
  sand: "모래",
  gravel: "자갈",
  slate: "슬레이트",
  basin: "분지",
  island: "섬",
  // 물·바다
  water: "물",
  sea: "바다",
  ocean: "바다",
  "sea waves": "파도",
  waves: "파도",
  wave: "파도",
  aquatic: "수생",
  "sea life": "해양생물",
  reef: "산호초",
  coast: "해안",
  coastline: "해안선",
  shoreline: "해안선",
  shore: "해변",
  waterfront: "물가",
  beach: "해변",
  lake: "호수",
  river: "강",
  creek: "개울",
  stream: "시내",
  lagoon: "석호",
  waterfall: "폭포",
  pond: "연못",
  wetland: "습지",
  marsh: "습지",
  ice: "얼음",
  glacier: "빙하",
  snow: "눈",
  frost: "서리",
  // 하늘·날씨·우주
  sky: "하늘",
  "red sky": "붉은 하늘",
  "azure sky": "푸른 하늘",
  "starry sky": "별하늘",
  cloud: "구름",
  clouds: "구름",
  cumulus: "적운",
  fog: "안개",
  mist: "안개",
  haze: "실안개",
  weather: "날씨",
  storm: "폭풍",
  atmosphere: "대기",
  light: "빛",
  sunlight: "햇빛",
  flare: "플레어",
  sun: "태양",
  sunset: "노을",
  sunrise: "일출",
  dawn: "새벽",
  dusk: "황혼",
  night: "밤",
  moon: "달",
  star: "별",
  stars: "별",
  astronomy: "천문",
  space: "우주",
  "outer space": "우주",
  universe: "우주",
  nebula: "성운",
  "milky way": "은하수",
  galaxy: "은하",
  sphere: "구체",
  fire: "불",
  smoke: "연기",
  // 계절
  summer: "여름",
  winter: "겨울",
  spring: "봄",
  autumn: "가을",
  fall: "가을",
  cold: "추위",
  // 식물
  plant: "식물",
  plants: "식물",
  flora: "식물",
  vegetation: "초목",
  tree: "나무",
  trees: "나무",
  "tree trunk": "나무 줄기",
  trunk: "줄기",
  forest: "숲",
  woodland: "숲",
  woods: "숲",
  grove: "숲",
  jungle: "정글",
  rainforest: "열대우림",
  bush: "덤불",
  shrub: "관목",
  grass: "풀",
  moss: "이끼",
  leaf: "잎",
  leaves: "잎",
  foliage: "잎",
  flower: "꽃",
  flowers: "꽃",
  blossom: "꽃",
  bloom: "꽃",
  petal: "꽃잎",
  petals: "꽃잎",
  pollen: "꽃가루",
  rose: "장미",
  daisy: "데이지",
  daisies: "데이지",
  tulip: "튤립",
  geranium: "제라늄",
  lily: "백합",
  sunflower: "해바라기",
  "flower arrangement": "꽃꽂이",
  "flower bouquet": "꽃다발",
  bouquet: "꽃다발",
  garden: "정원",
  "potted plant": "화분",
  "palm tree": "야자수",
  arecaceae: "야자과",
  pine: "소나무",
  fir: "전나무",
  spruce: "가문비나무",
  conifer: "침엽수",
  abies: "전나무",
  fern: "고사리",
  cactus: "선인장",
  // 동물
  animal: "동물",
  mammal: "포유류",
  wildlife: "야생동물",
  pet: "반려동물",
  canine: "개과",
  dog: "강아지",
  puppy: "강아지",
  "white dog": "흰 강아지",
  "golden retriever": "골든리트리버",
  husky: "허스키",
  "eskimo dog": "에스키모견",
  terrier: "테리어",
  wolf: "늑대",
  cat: "고양이",
  kitten: "새끼고양이",
  feline: "고양이과",
  manx: "맹크스",
  bird: "새",
  birds: "새",
  wildfowl: "들새",
  fowl: "가금",
  fish: "물고기",
  bear: "곰",
  horse: "말",
  cow: "소",
  deer: "사슴",
  rabbit: "토끼",
  fox: "여우",
  insect: "곤충",
  butterfly: "나비",
  invertebrate: "무척추동물",
  snout: "주둥이",
  // 사람
  person: "사람",
  people: "사람",
  human: "인간",
  man: "남성",
  woman: "여성",
  child: "아이",
  face: "얼굴",
  portrait: "인물",
  silhouette: "실루엣",
  head: "머리",
  finger: "손가락",
  hand: "손",
  body: "신체",
  // 활동·스포츠
  "leisure activities": "여가활동",
  sport: "스포츠",
  sports: "스포츠",
  hiking: "하이킹",
  camping: "캠핑",
  climbing: "등반",
  running: "달리기",
  swimming: "수영",
  cycling: "자전거",
  // 건축·도시
  building: "건물",
  buildings: "건물",
  architecture: "건축",
  house: "집",
  housing: "주택",
  home: "집",
  tower: "타워",
  spire: "첨탑",
  steeple: "첨탑",
  shelter: "쉼터",
  furniture: "가구",
  road: "길",
  path: "길",
  trail: "오솔길",
  highway: "고속도로",
  freeway: "고속도로",
  asphalt: "아스팔트",
  tarmac: "포장도로",
  handrail: "난간",
  banister: "난간",
  bridge: "다리",
  // 교통
  transportation: "교통",
  vehicle: "차량",
  car: "자동차",
  boat: "보트",
  ship: "배",
  train: "기차",
  airplane: "비행기",
  aircraft: "항공기",
  // 사물·색
  food: "음식",
  produce: "농산물",
  fruit: "과일",
  vegetable: "채소",
  pottery: "도자기",
  vase: "꽃병",
  jar: "항아리",
  ornament: "장식",
  toy: "장난감",
  clothing: "의류",
  apparel: "의류",
  wood: "목재",
  // 색
  blue: "파랑",
  green: "초록",
  red: "빨강",
  orange: "주황",
  white: "흰색",
  black: "검정",
  dark: "어두움",
  // 사진·예술
  photography: "사진",
  photo: "사진",
  art: "예술",
};

// 태그 하나를 한국어 라벨로. 매핑에 있으면 한글, 없고 한글이 섞여 있으면 원문(AI 태그), 그 외 영어는 null(숨김).
const HANGUL = /[가-힣]/;
export const toKoreanTag = (tag) => {
  if (typeof tag !== "string" || !tag.trim()) return null;
  const key = tag.trim().toLowerCase();
  if (TAG_KO[key]) return TAG_KO[key];
  if (HANGUL.test(tag)) return tag.trim(); // 이미 한국어(AI 이미지 태그 등)
  return null; // 매핑 없는 영어 태그는 숨김
};

// 태그 배열 → 한국어 라벨 배열(숨길 것 제거, 최대 max개, 중복 제거).
export const koreanTags = (tags, max = 3) => {
  if (!Array.isArray(tags)) return [];
  const out = [];
  for (const t of tags) {
    const ko = toKoreanTag(t);
    if (ko && !out.includes(ko)) out.push(ko);
    if (out.length >= max) break;
  }
  return out;
};
