apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DraWeTeam/drawe.git
    targetRevision: feature/eks-migration
    path: infra/k8s/overlays/dev/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: drawe-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
