apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drawe-prod

resources:
  - ../../../base/fastapi-embed

images:
  - name: drawe-fastapi
    newName: 933832340498.dkr.ecr.ap-northeast-2.amazonaws.com/drawe-prod-fastapi
    newTag: 0eaf9ee89ebabb4a573e340bcae3f1ee6590fd33

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: fastapi-embed-env
    literals:
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=prod,service.namespace=drawe
